#!/usr/bin/env python
"""simasl MriSignalFilter (spin echo) oracle -> tests/fixtures/mrsignal.txt.

    micromamba run -n simasl python tools/gen_mrsignal_fixtures.py

The written `signal_no_te` is simasl's spin-echo output DIVIDED BY exp(-TE/T2) voxel-wise, in
float64, because aslscan's mrsignal leaves transverse relaxation to the acquisition stage (spec:
division of labor). The generator asserts the factor is finite and nonzero everywhere before
dividing; a small enough positive T2 would underflow it. Exact T2 == 0 is not that case: simasl's
guard makes the factor exp(0) = 1 there, and one such voxel is included on purpose.
"""
import os

import numpy as np
from asldro.containers.image import NumpyImageContainer
from asldro.filters.mri_signal_filter import MriSignalFilter

SEED = 20260923
SHAPE = (6, 6, 2)
FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tests", "fixtures")
OUT = os.path.join(FIXTURES, "mrsignal.txt")
OUT_IR = os.path.join(FIXTURES, "mrsignal_ir.txt")
CASES = [(te, tr) for te in (0.010, 0.030) for tr in (2.0, 4.0, 10.0)]
# P3: inversion recovery. (te, tr, ti, excitation flip, inversion flip); the last row has an
# inversion angle of 0 (no inversion), the closed form the Rust test also checks.
IR_SEED = 20260924
IR_CASES = [(0.010, tr, ti, fa, fa_inv)
            for tr in (2.0, 4.0)
            for ti in (0.3, 1.0, 1.8)
            for (fa, fa_inv) in ((90.0, 180.0), (60.0, 120.0), (-30.0, 180.0), (60.0, 0.0))]
# P5: gradient echo. (te, tr, excitation flip); simasl's form keeps transverse coherence through
# exp(-TR/T2), and TR = 10 s makes that term below 1e-16 for every nonzero T2 drawn, where the
# spoiled form must agree too.
GE_SEED = 20261002
OUT_GE = os.path.join(FIXTURES, "mrsignal_ge.txt")
GE_CASES = [(te, tr, fa) for te in (0.010, 0.030) for tr in (2.0, 4.0, 10.0) for fa in (90.0, 60.0, 30.0, -30.0)]


def fmt(arr):
    return " ".join(repr(float(v)) for v in np.asarray(arr).ravel())


def voxels(rng, n):
    t1 = rng.uniform(0.5, 4.0, n)
    t1[rng.integers(n)] = 0.0       # simasl's guard: exp(0) = 1
    t2 = rng.uniform(0.03, 0.3, n)
    t2[rng.integers(n)] = 0.0       # factor exp(0) = 1; nothing to divide out
    t2s = rng.uniform(0.02, 0.2, n)
    m0 = rng.uniform(40.0, 100.0, n)
    return {k: v.reshape(SHAPE).astype(np.float64) for k, v in
            [("t1", t1), ("t2", t2), ("t2_star", t2s), ("m0", m0)]}


def run_filter(imgs, contrast, te, tr, ir=None, ge_fa=None):
    f = MriSignalFilter()
    for k, v in imgs.items():
        f.add_input(k, NumpyImageContainer(image=v))
    f.add_input(MriSignalFilter.KEY_ACQ_CONTRAST, contrast)
    f.add_input(MriSignalFilter.KEY_ECHO_TIME, float(te))
    f.add_input(MriSignalFilter.KEY_REPETITION_TIME, float(tr))
    if ir is not None:
        ti, fa, fa_inv = ir
        f.add_input(MriSignalFilter.KEY_INVERSION_TIME, float(ti))
        f.add_input(MriSignalFilter.KEY_EXCITATION_FLIP_ANGLE, float(fa))
        f.add_input(MriSignalFilter.KEY_INVERSION_FLIP_ANGLE, float(fa_inv))
    if ge_fa is not None:
        f.add_input(MriSignalFilter.KEY_EXCITATION_FLIP_ANGLE, float(ge_fa))
    f.run()
    sig = f.outputs[MriSignalFilter.KEY_IMAGE].image.astype(np.float64)
    # the transverse factor simasl applied: exp(-TE/T2*) for gradient echo, exp(-TE/T2) otherwise
    t2v = imgs["t2_star"] if contrast == "ge" else imgs["t2"]
    factor = np.exp(-np.divide(te, t2v, out=np.zeros_like(t2v), where=t2v != 0))
    assert np.all(np.isfinite(factor)) and np.all(factor != 0), "degenerate TE factor"
    return sig / factor


def main():
    rng = np.random.default_rng(SEED)
    n = int(np.prod(SHAPE))
    lines = [
        f"# simasl MriSignalFilter spin-echo fixtures -- seed {SEED}, {len(CASES)} cases, inputs float64, "
        "transverse factor exp(-TE/T2) divided out",
        "# generated by tools/gen_mrsignal_fixtures.py; do not edit by hand",
        "# per case: scalars <echo_time> <repetition_time>",
    ]
    for ci, (te, tr) in enumerate(CASES):
        imgs = voxels(rng, n)
        no_te = run_filter(imgs, "se", te, tr)
        lines.append(f"case {ci}")
        lines.append(f"scalars {te!r} {tr!r}")
        lines.append("t1 " + fmt(imgs["t1"]))
        lines.append("t2 " + fmt(imgs["t2"]))
        lines.append("m0 " + fmt(imgs["m0"]))
        lines.append("signal_no_te " + fmt(no_te))
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(OUT)}: {len(CASES)} cases")

    rng = np.random.default_rng(IR_SEED)
    lines = [
        f"# simasl MriSignalFilter inversion-recovery fixtures -- seed {IR_SEED}, {len(IR_CASES)} cases, "
        "inputs float64, transverse factor exp(-TE/T2) divided out",
        "# generated by tools/gen_mrsignal_fixtures.py; do not edit by hand",
        "# per case: scalars <echo_time> <repetition_time> <inversion_time> <excitation_flip_deg> <inversion_flip_deg>",
    ]
    for ci, (te, tr, ti, fa, fa_inv) in enumerate(IR_CASES):
        imgs = voxels(rng, n)
        no_te = run_filter(imgs, "ir", te, tr, ir=(ti, fa, fa_inv))
        lines.append(f"case {ci}")
        lines.append(f"scalars {te!r} {tr!r} {ti!r} {fa!r} {fa_inv!r}")
        lines.append("t1 " + fmt(imgs["t1"]))
        lines.append("t2 " + fmt(imgs["t2"]))
        lines.append("m0 " + fmt(imgs["m0"]))
        lines.append("signal_no_te " + fmt(no_te))
    with open(OUT_IR, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(OUT_IR)}: {len(IR_CASES)} cases")

    rng = np.random.default_rng(GE_SEED)
    lines = [
        f"# simasl MriSignalFilter gradient-echo fixtures -- seed {GE_SEED}, {len(GE_CASES)} cases, inputs float64, "
        "transverse factor exp(-TE/T2*) divided out",
        "# generated by tools/gen_mrsignal_fixtures.py; do not edit by hand",
        "# per case: scalars <echo_time> <repetition_time> <excitation_flip_deg>",
    ]
    for ci, (te, tr, fa) in enumerate(GE_CASES):
        imgs = voxels(rng, n)
        no_te = run_filter(imgs, "ge", te, tr, ge_fa=fa)
        lines.append(f"case {ci}")
        lines.append(f"scalars {te!r} {tr!r} {fa!r}")
        lines.append("t1 " + fmt(imgs["t1"]))
        lines.append("t2 " + fmt(imgs["t2"]))
        lines.append("m0 " + fmt(imgs["m0"]))
        lines.append("signal_no_te " + fmt(no_te))
    with open(OUT_GE, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(OUT_GE)}: {len(GE_CASES)} cases")


if __name__ == "__main__":
    main()
