#!/usr/bin/env python
"""simasl MriSignalFilter (spin echo) oracle -> tests/fixtures/mrsignal.txt.

    micromamba run -n simasl python tools/gen_mrsignal_fixtures.py

The written `signal_no_te` is simasl's spin-echo output DIVIDED BY exp(-TE/T2) voxel-wise, in
float64, because aslscan's mrsignal leaves transverse relaxation to the acquisition stage (spec:
division of labor). The generator asserts the factor is finite and nonzero everywhere before
dividing; a small enough positive T2 would underflow it. Exact T2 == 0 is not that case: simasl's
guard makes the factor exp(0) = 1 there, and one such voxel is included on purpose.
"""
import os

import numpy as np
from asldro.containers.image import NumpyImageContainer
from asldro.filters.mri_signal_filter import MriSignalFilter

SEED = 20260923
SHAPE = (6, 6, 2)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tests", "fixtures", "mrsignal.txt")
CASES = [(te, tr) for te in (0.010, 0.030) for tr in (2.0, 4.0, 10.0)]


def fmt(arr):
    return " ".join(repr(float(v)) for v in np.asarray(arr).ravel())


def main():
    rng = np.random.default_rng(SEED)
    n = int(np.prod(SHAPE))
    lines = [
        f"# simasl MriSignalFilter spin-echo fixtures -- seed {SEED}, {len(CASES)} cases, inputs float64, "
        "transverse factor exp(-TE/T2) divided out",
        "# generated by tools/gen_mrsignal_fixtures.py; do not edit by hand",
        "# per case: scalars <echo_time> <repetition_time>",
    ]
    for ci, (te, tr) in enumerate(CASES):
        t1 = rng.uniform(0.5, 4.0, n)
        t1[rng.integers(n)] = 0.0       # simasl's guard: exp(0) = 1, signal 0
        t2 = rng.uniform(0.03, 0.3, n)
        t2[rng.integers(n)] = 0.0       # factor exp(0) = 1; nothing to divide out
        t2s = rng.uniform(0.02, 0.2, n)
        m0 = rng.uniform(40.0, 100.0, n)
        imgs = {k: v.reshape(SHAPE).astype(np.float64) for k, v in
                [("t1", t1), ("t2", t2), ("t2_star", t2s), ("m0", m0)]}
        f = MriSignalFilter()
        for k, v in imgs.items():
            f.add_input(k, NumpyImageContainer(image=v))
        f.add_input(MriSignalFilter.KEY_ACQ_CONTRAST, "se")
        f.add_input(MriSignalFilter.KEY_ECHO_TIME, float(te))
        f.add_input(MriSignalFilter.KEY_REPETITION_TIME, float(tr))
        f.run()
        sig = f.outputs[MriSignalFilter.KEY_IMAGE].image.astype(np.float64)
        t2v = imgs["t2"]
        factor = np.exp(-np.divide(te, t2v, out=np.zeros_like(t2v), where=t2v != 0))
        assert np.all(np.isfinite(factor)) and np.all(factor != 0), f"case {ci}: degenerate TE factor"
        no_te = sig / factor
        lines.append(f"case {ci}")
        lines.append(f"scalars {te!r} {tr!r}")
        lines.append("t1 " + fmt(imgs["t1"]))
        lines.append("t2 " + fmt(t2v))
        lines.append("m0 " + fmt(imgs["m0"]))
        lines.append("signal_no_te " + fmt(no_te))
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(OUT)}: {len(CASES)} cases")


if __name__ == "__main__":
    main()
