#!/usr/bin/env python
"""simasl GkmFilter oracle -> tests/fixtures/gkm.txt (plain text, pure-std parsing).

    micromamba run -n simasl python tools/gen_gkm_fixtures.py

Every input is cast to float64 before the filter runs: simasl keeps the NIfTI dtype and a
float32 phantom makes perfusion_rate float32 (gkm_filter.py:105), which caps agreement at ~1e-7.
The header records the dtype so a regenerated fixture cannot silently be float32.

Per case the inputs are (6, 6, 2) arrays with deliberate edge voxels: exact zeros in perfusion
(the f = 0 path), transit times exactly equal to the signal time (the `t == dt` mask edge), the
CSF 1000 s sentinel, and one exact-zero tissue T1 (the guarded 1/T1). Values are written with
repr(), which round-trips float64 exactly.
"""
import os

import numpy as np
from asldro.containers.image import NumpyImageContainer
from asldro.filters.gkm_filter import GkmFilter

SEED = 20260923
SHAPE = (6, 6, 2)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tests", "fixtures", "gkm.txt")

# (label_type, label_duration, signal_time, label_efficiency, lambda_blood_brain, t1_arterial_blood)
CASES = [
    ("pcasl", 1.8, 3.6, 0.85, 0.9, 1.65),
    ("pcasl", 1.8, 2.0, 0.85, 0.9, 1.65),
    ("pcasl", 1.8, 1.0, 0.85, 0.9, 1.65),
    ("casl", 1.5, 3.0, 0.68, 0.9, 1.65),
    ("pasl", 0.7, 1.8, 0.98, 0.9, 1.65),
    ("pasl", 0.7, 1.2, 0.98, 0.9, 1.65),
    ("pasl", 0.7, 0.9, 0.98, 0.9, 1.65),
    ("pcasl", 1.8, 3.6, 0.85, 0.9, 0.0),
    ("pasl", 0.7, 1.8, 0.98, 0.9, 0.0),
    ("pcasl", 1.8, 3.6, 0.85, 0.0, 1.65),
    ("pcasl", 1.8, 3.6, 0.85, 1.0, 1.35),
    ("pasl", 0.5, 2.5, 0.98, 0.9, 1.35),
]


def draw_inputs(rng, signal_time):
    n = int(np.prod(SHAPE))
    f = rng.uniform(0.0, 90.0, n)
    f[rng.choice(n, n // 4, replace=False)] = 0.0
    dt = rng.uniform(0.3, 2.5, n)
    edge = rng.choice(n, 3, replace=False)
    dt[edge] = signal_time          # t == dt: the strict `<` puts these in the not-arrived mask
    dt[rng.integers(n)] = 1000.0    # the CSF never-arrives sentinel
    t1t = rng.uniform(0.8, 3.0, n)
    t1t[rng.integers(n)] = 0.0      # guarded 1/T1
    m0 = rng.uniform(50.0, 90.0, n)
    return [x.reshape(SHAPE).astype(np.float64) for x in (f, dt, t1t, m0)]


def fmt(arr):
    return " ".join(repr(float(v)) for v in np.asarray(arr).ravel())


def main():
    rng = np.random.default_rng(SEED)
    lines = [
        f"# simasl GkmFilter fixtures -- seed {SEED}, {len(CASES)} cases, inputs float64, shape {SHAPE}",
        "# generated by tools/gen_gkm_fixtures.py; do not edit by hand",
        "# per case: scalars <label_type> <label_duration> <signal_time> <label_efficiency> <lambda> <t1b>",
    ]
    for ci, (label_type, tau, t, alpha, lam, t1b) in enumerate(CASES):
        f, dt, t1t, m0 = draw_inputs(rng, t)
        g = GkmFilter()
        g.add_input(GkmFilter.KEY_PERFUSION_RATE, NumpyImageContainer(image=f))
        g.add_input(GkmFilter.KEY_TRANSIT_TIME, NumpyImageContainer(image=dt))
        g.add_input(GkmFilter.KEY_T1_TISSUE, NumpyImageContainer(image=t1t))
        g.add_input(GkmFilter.KEY_M0, NumpyImageContainer(image=m0))
        g.add_input(GkmFilter.KEY_LABEL_TYPE, label_type)
        g.add_input(GkmFilter.KEY_LABEL_DURATION, float(tau))
        g.add_input(GkmFilter.KEY_SIGNAL_TIME, float(t))
        g.add_input(GkmFilter.KEY_LABEL_EFFICIENCY, float(alpha))
        g.add_input(GkmFilter.KEY_LAMBDA_BLOOD_BRAIN, float(lam))
        g.add_input(GkmFilter.KEY_T1_ARTERIAL_BLOOD, float(t1b))
        g.run()
        delta_m = g.outputs[GkmFilter.KEY_DELTA_M].image
        assert delta_m.dtype == np.float64, delta_m.dtype
        assert np.all(np.isfinite(delta_m)), f"case {ci}: non-finite delta_m"
        lines.append(f"case {ci}")
        lines.append(f"scalars {label_type} {tau!r} {t!r} {alpha!r} {lam!r} {t1b!r}")
        lines.append("perfusion_rate " + fmt(f))
        lines.append("transit_time " + fmt(dt))
        lines.append("t1_tissue " + fmt(t1t))
        lines.append("m0 " + fmt(m0))
        lines.append("delta_m " + fmt(delta_m))
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(OUT)}: {len(CASES)} cases")


if __name__ == "__main__":
    main()
